import { NextIntlClientProvider } from 'next-intl';
import { Metadata } from 'next';
import { notFound } from 'next/navigation'; // Assuming 'notFound' is used for navigation handling
import './globals.css';

// Import 'Inter' font and define locales
const locales = ['en', 'es', 'zh'];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: {
    locale?: string;
  };
}

export default function LocaleLayout({ children, params: { locale } }: LocaleLayoutProps) {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale || '')) notFound();

  return (
    <NextIntlClientProvider>
      <html lang={locale}>
        {/* Ensure that the 'children' prop is of type ReactNode */}
        <body>{children}</body>
      </html>
    </NextIntlClientProvider>
  );
}
